#! /usr/bin/env python
import os

def configure(conf):
    conf.recurse(os.listdir(conf.path.abspath()), mandatory=False) 

def build(bld):
    bld.recurse(os.listdir(bld.path.abspath()), mandatory=False) 
