#! /usr/bin/env python
def build(bld):
    # COPY ALL ASSETS TO THE BUILD FOLDER.
    source_assets = bld.path.ant_glob('Assets/*.png')
    target_assets = []
    for source_asset in source_assets:
        target_assets.append(source_asset.get_bld())
    bld.copy(
        source = source_assets,
        target = target_assets,
        name = 'CopyAssets')
    
    # COMPILE THE GAME.
    bld.program(
        use = ['sfml', 'Box2D', 'CopyAssets'],
        source = bld.path.ant_glob('Code/**/*.cpp'),
        includes = 'Code',
        target = 'ExampleGame')